version: '{build}'
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(semver)
  assembly_file_version: $(semver).{build}
  assembly_informational_version: '{version}'
init:
  - git config --global core.autocrlf input
install:
- ps: >-
    set -name semver -scope global -value (get-content .\semver.txt)

    $env:semver = $semver

    if ("$env:appveyor_repo_tag_name" -ne "releases/$semver") {
      $env:package_suffix = "-alpha$env:appveyor_build_number" }

    update-appveyorbuild -Version "$env:semver$env:package_suffix"
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\BuildAndPack.ps1 -VersionSuffix "$env:package_suffix" -GitCommitId "$env:appveyor_repo_commit" -MsBuildArgs @(, "/logger:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll") -CIBuild
skip_branch_with_pr: true
skip_tags: false
skip_commits:
  files:
    - '**/*.md'
artifacts:
- path: packages/obj/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  api_key:
    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package
